name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '10'

    - name: Install dependencies
      run: npm install

#    - name: Run tests
#      run: npm test

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1
      with:
        sonarqube-url: 'http://localhost:9000'
        scanner-version: '4.5.0'
        project-key: 'nodejs-hello-world'
        project-name: 'Node.js Hello World'
        project-version: '1.0.0'
        sources: '.'
        extra-properties: |
          sonar.javascript.file.suffixes=.js
          sonar.coverage.exclusions=node_modules/**/*,test/**/*
#
#    - name: Build Docker image
#      run: |
#        docker build -t your-docker-username/nodejs-hello-world:latest .
#        docker tag your-docker-username/nodejs-hello-world:latest your-docker-username/nodejs-hello-world:1.0.0
#
#    - name: Push Docker image
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#      run: |
#        docker push your-docker-username/nodejs-hello-world:latest
#        docker push your-docker-username/nodejs-hello-world:1.0.0
#
