name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

#    - name: Install dependencies
#      run: npm ci

#    - name: Build Node.js app
#      run: npm run build

    - name: Stand up SonarQube instance
      uses: docker/compose@v2
      with:
        file: docker-compose.yml
        command: up -d

    - name: Analyze code with SonarQube
      uses: sonarsource/sonarqube-scan-action@master
      with:
        sonar-host-url: http://localhost:9000
        sonar-login: ${{ secrets.SONAR_TOKEN }}

    - name: Push container image to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: username/nodejs-hello-world:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run image from DockerHub on local machine
      run: docker run -p 80:80 -d username/nodejs-hello-world:${{ github.sha }}

